/**
 * @file ssmbattery.c
 *
 * @brief This source file was generated by cantools version 40.2.0 Mon Mar 17 18:55:04 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "ssmbattery.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int ssmbattery_query_frame_pack(
    uint8_t *dst_p,
    const struct ssmbattery_query_frame_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->data_byte_0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->data_byte_1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->data_byte_2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->data_byte_3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->data_byte_4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->data_byte_5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->data_byte_6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->data_byte_7, 0u, 0xffu);

    return (8);
}

int ssmbattery_query_frame_unpack(
    struct ssmbattery_query_frame_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->data_byte_0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->data_byte_1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->data_byte_2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->data_byte_3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->data_byte_4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->data_byte_5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->data_byte_6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->data_byte_7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_query_frame_init(struct ssmbattery_query_frame_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_query_frame_t));

    return 0;
}

uint8_t ssmbattery_query_frame_data_byte_0_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_0_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_1_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_1_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_2_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_2_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_3_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_3_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_4_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_4_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_5_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_5_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_6_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_6_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_query_frame_data_byte_7_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_query_frame_data_byte_7_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_query_frame_data_byte_7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_cell_voltage_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_cell_voltage_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->module, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->volt1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->volt1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->volt2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->volt2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->volt3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->volt3, 0u, 0xffu);

    return (8);
}

int ssmbattery_cell_voltage_information_unpack(
    struct ssmbattery_cell_voltage_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->module = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->volt1 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->volt1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->volt2 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->volt2 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->volt3 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->volt3 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);

    return (0);
}

int ssmbattery_cell_voltage_information_init(struct ssmbattery_cell_voltage_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_cell_voltage_information_t));

    return 0;
}

uint8_t ssmbattery_cell_voltage_information_module_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_cell_voltage_information_module_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_cell_voltage_information_module_is_in_range(uint8_t value)
{
    return (value >= 1u);
}

uint16_t ssmbattery_cell_voltage_information_volt1_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_information_volt1_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_information_volt1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ssmbattery_cell_voltage_information_volt2_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_information_volt2_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_information_volt2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ssmbattery_cell_voltage_information_volt3_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_information_volt3_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_information_volt3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_cell_temperature_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_cell_temperature_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->module, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->temper1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->temper2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->temper3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->temper4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->temper5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->temper6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->temper7, 0u, 0xffu);

    return (8);
}

int ssmbattery_cell_temperature_information_unpack(
    struct ssmbattery_cell_temperature_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->module = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->temper1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->temper2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->temper3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->temper4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->temper5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->temper6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->temper7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_cell_temperature_information_init(struct ssmbattery_cell_temperature_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_cell_temperature_information_t));

    return 0;
}

uint8_t ssmbattery_cell_temperature_information_module_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_cell_temperature_information_module_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_cell_temperature_information_module_is_in_range(uint8_t value)
{
    return (value >= 1u);
}

uint8_t ssmbattery_cell_temperature_information_temper1_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper1_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper2_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper2_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper3_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper3_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper4_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper4_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper5_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper5_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper6_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper6_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_temperature_information_temper7_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_cell_temperature_information_temper7_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_cell_temperature_information_temper7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_total_information_0_pack(
    uint8_t *dst_p,
    const struct ssmbattery_total_information_0_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->sum_v, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->sum_v, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->curr, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->curr, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->soc, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->soc, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->life, 0u, 0xffu);

    return (8);
}

int ssmbattery_total_information_0_unpack(
    struct ssmbattery_total_information_0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sum_v = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->sum_v |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->curr = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->curr |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->soc = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->soc |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->life = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int ssmbattery_total_information_0_init(struct ssmbattery_total_information_0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_total_information_0_t));

    return 0;
}

uint16_t ssmbattery_total_information_0_sum_v_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ssmbattery_total_information_0_sum_v_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ssmbattery_total_information_0_sum_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ssmbattery_total_information_0_curr_encode(float value)
{
    return (uint16_t)((value - -3000.0f) / 0.1f);
}

float ssmbattery_total_information_0_curr_decode(uint16_t value)
{
    return (((float)value * 0.1f) + -3000.0f);
}

bool ssmbattery_total_information_0_curr_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

uint16_t ssmbattery_total_information_0_soc_encode(float value)
{
    return (uint16_t)(value / 0.1f);
}

float ssmbattery_total_information_0_soc_decode(uint16_t value)
{
    return ((float)value * 0.1f);
}

bool ssmbattery_total_information_0_soc_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

uint8_t ssmbattery_total_information_0_life_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_total_information_0_life_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_total_information_0_life_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_total_information_1_pack(
    uint8_t *dst_p,
    const struct ssmbattery_total_information_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->power, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->power, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->total_energy, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->total_energy, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mos_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->board_temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->heat_temp, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->heat_cur, 0u, 0xffu);

    return (8);
}

int ssmbattery_total_information_1_unpack(
    struct ssmbattery_total_information_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->power = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->power |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->total_energy = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->total_energy |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->mos_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->board_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->heat_temp = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->heat_cur = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_total_information_1_init(struct ssmbattery_total_information_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_total_information_1_t));

    return 0;
}

uint16_t ssmbattery_total_information_1_power_encode(float value)
{
    return (uint16_t)(value);
}

float ssmbattery_total_information_1_power_decode(uint16_t value)
{
    return ((float)value);
}

bool ssmbattery_total_information_1_power_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t ssmbattery_total_information_1_total_energy_encode(float value)
{
    return (uint16_t)(value);
}

float ssmbattery_total_information_1_total_energy_decode(uint16_t value)
{
    return ((float)value);
}

bool ssmbattery_total_information_1_total_energy_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_total_information_1_mos_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_total_information_1_mos_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_total_information_1_mos_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_total_information_1_board_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_total_information_1_board_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_total_information_1_board_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_total_information_1_heat_temp_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_total_information_1_heat_temp_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_total_information_1_heat_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_total_information_1_heat_cur_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_total_information_1_heat_cur_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_total_information_1_heat_cur_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_cell_voltage_statistical_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_cell_voltage_statistical_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_v, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_v, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->max_v_no, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->min_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->min_v, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->min_v_no, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->diff_v, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->diff_v, 0u, 0xffu);

    return (8);
}

int ssmbattery_cell_voltage_statistical_information_unpack(
    struct ssmbattery_cell_voltage_statistical_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_v = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_v |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_v_no = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->min_v = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->min_v |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->min_v_no = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->diff_v = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->diff_v |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_cell_voltage_statistical_information_init(struct ssmbattery_cell_voltage_statistical_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_cell_voltage_statistical_information_t));

    return 0;
}

uint16_t ssmbattery_cell_voltage_statistical_information_max_v_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_statistical_information_max_v_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_statistical_information_max_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_voltage_statistical_information_max_v_no_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_cell_voltage_statistical_information_max_v_no_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_cell_voltage_statistical_information_max_v_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t ssmbattery_cell_voltage_statistical_information_min_v_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_statistical_information_min_v_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_statistical_information_min_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_cell_voltage_statistical_information_min_v_no_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_cell_voltage_statistical_information_min_v_no_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_cell_voltage_statistical_information_min_v_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t ssmbattery_cell_voltage_statistical_information_diff_v_encode(float value)
{
    return (uint16_t)(value / 0.001f);
}

float ssmbattery_cell_voltage_statistical_information_diff_v_decode(uint16_t value)
{
    return ((float)value * 0.001f);
}

bool ssmbattery_cell_voltage_statistical_information_diff_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_unit_temperature_statistical_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_unit_temperature_statistical_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->max_t, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->max_t_no, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->ik_b, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->min_t, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->diff_t, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->reserved0, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved1, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved2, 0u, 0xffu);

    return (8);
}

int ssmbattery_unit_temperature_statistical_information_unpack(
    struct ssmbattery_unit_temperature_statistical_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_t = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->max_t_no = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ik_b = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->min_t = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->diff_t = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->reserved0 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved1 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved2 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_unit_temperature_statistical_information_init(struct ssmbattery_unit_temperature_statistical_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_unit_temperature_statistical_information_t));

    return 0;
}

uint8_t ssmbattery_unit_temperature_statistical_information_max_t_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_unit_temperature_statistical_information_max_t_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_unit_temperature_statistical_information_max_t_is_in_range(uint8_t value)
{
    return (value <= 165u);
}

uint8_t ssmbattery_unit_temperature_statistical_information_max_t_no_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_max_t_no_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_max_t_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_unit_temperature_statistical_information_ik_b_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_ik_b_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_ik_b_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_unit_temperature_statistical_information_min_t_encode(float value)
{
    return (uint8_t)(value - -40.0f);
}

float ssmbattery_unit_temperature_statistical_information_min_t_decode(uint8_t value)
{
    return ((float)value + -40.0f);
}

bool ssmbattery_unit_temperature_statistical_information_min_t_is_in_range(uint8_t value)
{
    return (value <= 165u);
}

uint8_t ssmbattery_unit_temperature_statistical_information_diff_t_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_diff_t_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_diff_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_unit_temperature_statistical_information_reserved0_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_reserved0_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_reserved0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_unit_temperature_statistical_information_reserved1_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_reserved1_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_unit_temperature_statistical_information_reserved2_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_unit_temperature_statistical_information_reserved2_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_unit_temperature_statistical_information_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_status_information_0_pack(
    uint8_t *dst_p,
    const struct ssmbattery_status_information_0_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->chg_mos_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->dis_chg_mos_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->pre_mos_state, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->heat_mos_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fan_mos_state, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->reserved0, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved1, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved2, 0u, 0xffu);

    return (8);
}

int ssmbattery_status_information_0_unpack(
    struct ssmbattery_status_information_0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->chg_mos_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dis_chg_mos_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->pre_mos_state = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->heat_mos_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fan_mos_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->reserved0 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved1 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved2 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_status_information_0_init(struct ssmbattery_status_information_0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_status_information_0_t));

    return 0;
}

uint8_t ssmbattery_status_information_0_chg_mos_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_chg_mos_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_chg_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_dis_chg_mos_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_dis_chg_mos_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_dis_chg_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_pre_mos_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_pre_mos_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_pre_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_heat_mos_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_heat_mos_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_heat_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_fan_mos_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_fan_mos_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_fan_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_reserved0_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_reserved0_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_reserved0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_reserved1_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_reserved1_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_0_reserved2_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_0_reserved2_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_0_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_status_information_1_pack(
    uint8_t *dst_p,
    const struct ssmbattery_status_information_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bat_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->chg_detect, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->loard_detect, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->do_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->di_state, 0u, 0xffu);

    return (8);
}

int ssmbattery_status_information_1_unpack(
    struct ssmbattery_status_information_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bat_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->chg_detect = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->loard_detect = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->do_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->di_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int ssmbattery_status_information_1_init(struct ssmbattery_status_information_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_status_information_1_t));

    return 0;
}

uint8_t ssmbattery_status_information_1_bat_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_1_bat_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_1_bat_state_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

uint8_t ssmbattery_status_information_1_chg_detect_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_1_chg_detect_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_1_chg_detect_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ssmbattery_status_information_1_loard_detect_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_1_loard_detect_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_1_loard_detect_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ssmbattery_status_information_1_do_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_1_do_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_1_do_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_1_di_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_1_di_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_1_di_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_status_information_2_pack(
    uint8_t *dst_p,
    const struct ssmbattery_status_information_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cell_number, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ntc_number, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->remain_capacity1, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->remain_capacity2, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->remain_capacity3, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->remain_capacity4, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->cycle_time_h, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->cycle_time_l, 0u, 0xffu);

    return (8);
}

int ssmbattery_status_information_2_unpack(
    struct ssmbattery_status_information_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_number = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ntc_number = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->remain_capacity1 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->remain_capacity2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->remain_capacity3 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->remain_capacity4 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->cycle_time_h = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->cycle_time_l = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_status_information_2_init(struct ssmbattery_status_information_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_status_information_2_t));

    return 0;
}

uint8_t ssmbattery_status_information_2_cell_number_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_cell_number_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_cell_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_ntc_number_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_ntc_number_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_ntc_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_remain_capacity1_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_remain_capacity1_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_remain_capacity1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_remain_capacity2_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_remain_capacity2_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_remain_capacity2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_remain_capacity3_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_remain_capacity3_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_remain_capacity3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_remain_capacity4_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_remain_capacity4_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_remain_capacity4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_cycle_time_h_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_cycle_time_h_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_cycle_time_h_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_status_information_2_cycle_time_l_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_status_information_2_cycle_time_l_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_status_information_2_cycle_time_l_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_hardware_and_battery_failure_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_hardware_and_battery_failure_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->voltage_faults, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->temp_faults, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->overcurrent_faults, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->pressure_temp_faults, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mos_faults, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->system_faults, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->module_faults, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->balance_faults, 0u, 0xffu);

    return (8);
}

int ssmbattery_hardware_and_battery_failure_information_unpack(
    struct ssmbattery_hardware_and_battery_failure_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage_faults = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->temp_faults = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->overcurrent_faults = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->pressure_temp_faults = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->mos_faults = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->system_faults = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->module_faults = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->balance_faults = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int ssmbattery_hardware_and_battery_failure_information_init(struct ssmbattery_hardware_and_battery_failure_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_hardware_and_battery_failure_information_t));

    return 0;
}

uint8_t ssmbattery_hardware_and_battery_failure_information_voltage_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_voltage_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_voltage_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_temp_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_temp_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_temp_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_overcurrent_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_overcurrent_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_overcurrent_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_pressure_temp_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_pressure_temp_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_pressure_temp_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_mos_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_mos_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_mos_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_system_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_system_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_system_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_module_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_module_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_module_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_hardware_and_battery_failure_information_balance_faults_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_hardware_and_battery_failure_information_balance_faults_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_hardware_and_battery_failure_information_balance_faults_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_charging_information_pack(
    uint8_t *dst_p,
    const struct ssmbattery_charging_information_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->rest_chg_time, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rest_chg_time, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->wakeup_source, 0u, 0xffu);

    return (8);
}

int ssmbattery_charging_information_unpack(
    struct ssmbattery_charging_information_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->rest_chg_time = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rest_chg_time |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->wakeup_source = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int ssmbattery_charging_information_init(struct ssmbattery_charging_information_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_charging_information_t));

    return 0;
}

uint16_t ssmbattery_charging_information_rest_chg_time_encode(float value)
{
    return (uint16_t)(value);
}

float ssmbattery_charging_information_rest_chg_time_decode(uint16_t value)
{
    return ((float)value);
}

bool ssmbattery_charging_information_rest_chg_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_charging_information_wakeup_source_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_charging_information_wakeup_source_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_charging_information_wakeup_source_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

int ssmbattery_limiting_pack(
    uint8_t *dst_p,
    const struct ssmbattery_limiting_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->limit_cur_state, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->limic_cur, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->limic_cur, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->pwm_duty, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->pwm_duty, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved0, 0u, 0xffu);

    return (8);
}

int ssmbattery_limiting_unpack(
    struct ssmbattery_limiting_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->limit_cur_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->limic_cur = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->limic_cur |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->pwm_duty = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->pwm_duty |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->reserved0 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

int ssmbattery_limiting_init(struct ssmbattery_limiting_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_limiting_t));

    return 0;
}

uint8_t ssmbattery_limiting_limit_cur_state_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_limiting_limit_cur_state_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_limiting_limit_cur_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ssmbattery_limiting_limic_cur_encode(float value)
{
    return (uint16_t)((value - -30000.0f) / 0.1f);
}

float ssmbattery_limiting_limic_cur_decode(uint16_t value)
{
    return (((float)value * 0.1f) + -30000.0f);
}

bool ssmbattery_limiting_limic_cur_is_in_range(uint16_t value)
{
    return (value >= 270000u);
}

uint16_t ssmbattery_limiting_pwm_duty_encode(float value)
{
    return (uint16_t)(value);
}

float ssmbattery_limiting_pwm_duty_decode(uint16_t value)
{
    return ((float)value);
}

bool ssmbattery_limiting_pwm_duty_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ssmbattery_limiting_reserved0_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_limiting_reserved0_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_limiting_reserved0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ssmbattery_fault_pack(
    uint8_t *dst_p,
    const struct ssmbattery_fault_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->page_no, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fault_bits, 0u, 0xffu);

    return (8);
}

int ssmbattery_fault_unpack(
    struct ssmbattery_fault_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->page_no = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fault_bits = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int ssmbattery_fault_init(struct ssmbattery_fault_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ssmbattery_fault_t));

    return 0;
}

uint8_t ssmbattery_fault_page_no_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_fault_page_no_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_fault_page_no_is_in_range(uint8_t value)
{
    return (value >= 1u);
}

uint8_t ssmbattery_fault_fault_bits_encode(float value)
{
    return (uint8_t)(value);
}

float ssmbattery_fault_fault_bits_decode(uint8_t value)
{
    return ((float)value);
}

bool ssmbattery_fault_fault_bits_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
