#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef HAL_TORQEEDO_ENABLED
#define HAL_TORQEEDO_ENABLED BOARD_FLASH_SIZE > 1024

#define HAL_TORQEEDO_IFACE_TORQLINK_CAN      1
#define HAL_TORQEEDO_IFACE_TORQBUS_RS485     0

#endif
