#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_CAN_SLCAN_ENABLED
#define AP_CAN_SLCAN_ENABLED HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#ifndef HAL_NMEA2K_ENABLED
#define HAL_NMEA2K_ENABLED HAL_CANMANAGER_ENABLED
#endif